#ifndef SHARED_H_
#define SHARED_H_

#if RTOS_CORE_TIMER > RTOS_P_MAX_TIMER
#	error Invalid timer selected
#endif

#if RTOS_CORE_TIMER == RTOS_TIMER0
#	define RTOS_TIMER_INIT RTOS_TIMER0_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER0_VECTOR
#elif RTOS_CORE_TIMER == RTOS_TIMER1
#	define RTOS_TIMER_INIT RTOS_TIMER1_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER1_VECTOR
#elif RTOS_CORE_TIMER == RTOS_TIMER2
#	define RTOS_TIMER_INIT RTOS_TIMER2_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER2_VECTOR
#elif RTOS_CORE_TIMER == RTOS_TIMER3
#	define RTOS_TIMER_INIT RTOS_TIMER3_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER3_VECTOR
#elif RTOS_RTOS_CORE_TIMER == RTOS_TIMER4
#	define RTOS_TIMER_INIT RTOS_TIMER4_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER4_VECTOR
#elif RTOS_CORE_TIMER == RTOS_TIMER5
#	define RTOS_TIMER_INIT RTOS_TIMER5_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER5_VECTOR
#elif RTOS_CORE_TIMER == RTOS_TIMER6
#	define RTOS_TIMER_INIT RTOS_TIMER6_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER6_VECTOR
#elif RTOS_CORE_TIMER == RTOS_TIMER7
#	define RTOS_TIMER_INIT RTOS_TIMER7_INIT
#	define RTOS_TIMER_VECTOR RTOS_TIMER7_VECTOR
#endif


#endif /* SHARED_H_ */
